sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '5'
  - '6'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test:with-coverage
  - npm run test:check-coverage
after_success:
  - npm run test:publish-coverage
  # No need to build as it is done in the prepublish script
  - npm run semantic-release
branches:
  only:
    - master
    - /^greenkeeper-.*$/
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
